import { test } from 'node:test';
import assert from 'node:assert/strict';
import { ContractFactory, JsonRpcProvider, ZeroAddress } from 'ethers';
import { compile } from '../scripts/compile.mjs';

test('purchase, proportional income, claims, transfers, and operator boundaries', async () => {
  const provider = new JsonRpcProvider('http://127.0.0.1:8545', undefined, { cacheTimeout: -1 });
  try {
    assert.equal((await provider.getNetwork()).chainId, 31337n, 'Tests require the disposable local chain.');
    const [operator, alice, budi] = await Promise.all([0, 1, 2].map(i => provider.getSigner(i)));
    const artifact = compile();
    const c = await new ContractFactory(artifact.abi, artifact.bytecode, operator).deploy();
    await c.waitForDeployment();
    const price = await c.SHARE_PRICE(), scale = await c.WEI_PER_DEMO_IDR();
    const A = await alice.getAddress(), B = await budi.getAddress(), O = await operator.getAddress();
    assert.equal(await c.totalSupply(), 1000n);
    await assert.rejects(c.connect(alice).buyShares(0, { value: 0 }));
    await assert.rejects(c.connect(alice).buyShares(100, { value: price }));
    await assert.rejects(c.connect(alice).buyShares(1001, { value: price * 1001n }));
    await assert.rejects(c.buyShares(1, { value: price }));
    await assert.rejects(c.transfer(A, 1));
    await (await c.connect(alice).buyShares(100, { value: price * 100n })).wait();
    await (await c.connect(budi).buyShares(50, { value: price * 50n })).wait();
    assert.equal(await c.balanceOf(A), 100n);
    assert.equal(await c.availableShares(), 850n);
    const deposit = 1200000n * scale;
    await assert.rejects(c.connect(alice).publishReport(202610, 1200, 400000, 200000, { value: deposit }));
    await assert.rejects(c.publishReport(202613, 1200, 400000, 200000, { value: deposit }));
    await assert.rejects(c.publishReport(202610, 1200, 400000, 200000, { value: 1n }));
    await assert.rejects(c.publishReport(202610, 1200, 1800000, 1, { value: deposit }));
    await (await c.publishReport(202610, 1200, 400000, 200000, { value: deposit })).wait();
    assert.equal(await c.claimable(A), deposit / 10n);
    assert.equal(await c.claimable(B), deposit / 20n);
    assert.equal(await c.claimable(O), deposit * 85n / 100n);
    await assert.rejects(c.publishReport(202610, 1200, 400000, 200000, { value: deposit }));
    await assert.rejects(c.publishReport(202609, 1200, 400000, 200000, { value: deposit }));
    await (await c.connect(alice).buyShares(100, { value: price * 100n })).wait();
    assert.equal(await c.claimable(A), deposit / 10n, 'Later purchases cannot receive old income.');
    await (await c.connect(alice).transfer(B, 100)).wait();
    assert.equal(await c.claimable(A), deposit / 10n, 'Earned income stays with the sender.');
    assert.equal(await c.claimable(B), deposit / 20n, 'Receiving shares does not receive old income.');
    await (await c.connect(budi).approve(A, 10)).wait();
    await (await c.connect(alice).transferFrom(B, A, 10)).wait();
    assert.equal(await c.claimable(B), deposit / 20n, 'transferFrom preserves previously earned income.');
    await assert.rejects(c.connect(alice).transfer(ZeroAddress, 1));
    await assert.rejects(c.connect(alice).transfer(B, 1001));
    await (await c.publishReport(202611, 1200, 400000, 200000, { value: deposit })).wait();
    assert.equal(await c.claimable(A), deposit * 21n / 100n);
    assert.equal(await c.claimable(B), deposit * 19n / 100n);
    const due = await c.claimable(A);
    const before = await provider.getBalance(A);
    const claim = await (await c.connect(alice).claimRevenue()).wait();
    const after = await provider.getBalance(A);
    assert.equal(after - before + claim.fee, due, 'Claim pays actual test ETH.');
    assert.equal(await c.totalClaimed(A), due);
    assert.equal(await c.claimable(A), 0n);
    await assert.rejects(c.connect(alice).claimRevenue());
    await assert.rejects(c.connect(alice).withdrawSaleProceeds());
    await (await c.withdrawSaleProceeds()).wait();
    assert.equal(await c.saleProceeds(), 0n);
    assert.equal(await provider.getBalance(await c.getAddress()), (await c.claimable(B)) + (await c.claimable(O)), 'Withdrawing sale proceeds preserves all unpaid holder income.');
    await (await c.connect(budi).claimRevenue()).wait();
    await (await c.claimRevenue()).wait();
    assert.equal(await provider.getBalance(await c.getAddress()), 0n, 'Every deposited wei is accounted for.');
    await (await c.connect(budi).buyShares(750, { value: price * 750n })).wait();
    assert.equal(await c.availableShares(), 0n);
    await assert.rejects(c.connect(alice).buyShares(1, { value: price }));
    console.log('Verified actual EVM transactions, proportional payouts, no retroactive income, no double claims, and reserved funds.');
  } finally { provider.destroy(); }
});
