import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createSimulation, demoAccounts } from '../src/simulation.js';

test('simulation preserves money, accrued income, reloads, and role restrictions', () => {
  const values = new Map();
  const storage = { getItem: k => values.get(k), setItem: (k, v) => values.set(k, v), removeItem: k => values.delete(k) };
  let demo = createSimulation(storage);
  const [operator, alice, budi] = demoAccounts;
  const scale = 1000000000n;
  const A = demo.forAccount(alice), O = demo.forAccount(operator);
  A.buyShares(100, { value: 10000000n * scale });
  assert.equal(demo.snapshot(alice).cash, 90000000);
  assert.throws(() => A.buyShares(-1, { value: -100000n * scale }));
  assert.throws(() => A.publishReport(202610, 4000, 800000, 200000, { value: 5000000n * scale }));
  O.publishReport(202610, 4000, 800000, 200000, { value: 5000000n * scale });
  assert.equal(demo.snapshot(alice).claimable, 500000n * scale);
  assert.throws(() => O.publishReport(202610, 4000, 800000, 200000, { value: 5000000n * scale }));
  A.transfer(budi, 10);
  assert.equal(demo.snapshot(alice).claimable, 500000n * scale);
  assert.equal(demo.snapshot(budi).claimable, 0n);
  demo.forAccount(budi).buyShares(50, { value: 5000000n * scale });
  assert.equal(demo.snapshot(budi).claimable, 0n);
  A.claimRevenue();
  assert.equal(demo.snapshot(alice).cash, 90500000);
  assert.throws(() => A.claimRevenue());
  O.withdrawSaleProceeds();
  assert.equal(demo.snapshot(operator).claimable, 4500000n * scale);
  O.publishReport(202611, 1, 1, 0, { value: 1499n * scale });
  assert.equal(demo.snapshot(alice).claimable, 134910000000n);
  const expected = demo.snapshot(alice);
  demo = createSimulation(storage);
  assert.deepEqual(demo.snapshot(alice), expected);
  const snapshots = demoAccounts.map(a => demo.snapshot(a));
  assert.equal(snapshots.reduce((s, x) => s + x.balance, 0), 1000);
  assert.equal(snapshots.reduce((s, x) => s + BigInt(Math.round(x.cash * 1000)) * 1000000n + x.claimable, 0n) + demo.snapshot(operator).proceeds, 300000000n * scale);
  const before = demo.snapshot(alice);
  storage.setItem = () => { throw new Error('Storage full'); };
  assert.throws(() => demo.forAccount(alice).buyShares(1, { value: 100000n * scale }), /Storage full/);
  assert.deepEqual(demo.snapshot(alice), before);
  demo.reset();
  assert.equal(demo.snapshot(alice).balance, 0);
  assert.equal(demo.snapshot(operator).balance, 1000);
  assert.equal(demo.snapshot(alice).logs.length, 0);
});
